import type { ThemeDefinition } from "./slots";

/**
 * Curated preset themes (docs/PLAN.md §7 D5 — ~40 verified presets at v1.0,
 * not an unverified 170). Each defines the 8 required core slots; widgets
 * needing extension-slot colors (ring, fire, ...) fall back to core slots
 * automatically unless a theme overrides them below.
 */
export const THEMES: Record<string, ThemeDefinition> = {
  default: {
    name: "default",
    label: "Default (Light)",
    mode: "light",
    core: {
      background: "#ffffff",
      border: "#e4e2e2",
      title: "#2f80ed",
      text: "#434d58",
      icon: "#4c71f2",
      accent: "#4c71f2",
      stroke: "#e4e2e2",
      muted: "#666666",
    },
  },
  dark: {
    name: "dark",
    label: "Dark",
    mode: "dark",
    core: {
      background: "#151515",
      border: "#e4e2e2",
      title: "#fff",
      text: "#9f9f9f",
      icon: "#79ff97",
      accent: "#79ff97",
      stroke: "#e4e2e2",
      muted: "#9f9f9f",
    },
  },
  transparent: {
    name: "transparent",
    label: "Transparent",
    mode: "dark",
    core: {
      background: "transparent",
      border: "#e4e2e2",
      title: "#fff",
      text: "#9f9f9f",
      icon: "#79ff97",
      accent: "#79ff97",
      stroke: "#e4e2e2",
      muted: "#9f9f9f",
    },
  },
  highcontrast: {
    name: "highcontrast",
    label: "High Contrast",
    mode: "dark",
    core: {
      background: "#000000",
      border: "#e4e2e2",
      title: "#fff",
      text: "#fff",
      icon: "#fff700",
      accent: "#fff700",
      stroke: "#e4e2e2",
      muted: "#fff",
    },
  },
  radical: {
    name: "radical",
    label: "Radical",
    mode: "dark",
    core: {
      background: "#141321",
      border: "#e4e2e2",
      title: "#fe428e",
      text: "#a9fef7",
      icon: "#f8d847",
      accent: "#fe428e",
      stroke: "#e4e2e2",
      muted: "#a9fef7",
    },
  },
  merko: {
    name: "merko",
    label: "Merko",
    mode: "dark",
    core: {
      background: "#0a0f0b",
      border: "#e4e2e2",
      title: "#abd200",
      text: "#68b587",
      icon: "#b7d364",
      accent: "#abd200",
      stroke: "#e4e2e2",
      muted: "#68b587",
    },
  },
  gruvbox: {
    name: "gruvbox",
    label: "Gruvbox",
    mode: "dark",
    core: {
      background: "#282828",
      border: "#e4e2e2",
      title: "#fabd2f",
      text: "#8ec07c",
      icon: "#fe8019",
      accent: "#fabd2f",
      stroke: "#e4e2e2",
      muted: "#8ec07c",
    },
  },
  "gruvbox-light": {
    name: "gruvbox-light",
    label: "Gruvbox Light",
    mode: "light",
    core: {
      background: "#fbf1c7",
      border: "#3c3836",
      title: "#b57614",
      text: "#665c54",
      icon: "#af3a03",
      accent: "#b57614",
      stroke: "#3c3836",
      muted: "#665c54",
    },
  },
  tokyonight: {
    name: "tokyonight",
    label: "Tokyo Night",
    mode: "dark",
    core: {
      background: "#1a1b27",
      border: "#e4e2e2",
      title: "#70a5fd",
      text: "#38bdae",
      icon: "#bf91f3",
      accent: "#70a5fd",
      stroke: "#e4e2e2",
      muted: "#38bdae",
    },
  },
  onedark: {
    name: "onedark",
    label: "One Dark",
    mode: "dark",
    core: {
      background: "#282c34",
      border: "#e4e2e2",
      title: "#e4bf7a",
      text: "#df6d74",
      icon: "#8eb573",
      accent: "#e4bf7a",
      stroke: "#e4e2e2",
      muted: "#df6d74",
    },
  },
  cobalt: {
    name: "cobalt",
    label: "Cobalt",
    mode: "dark",
    core: {
      background: "#193549",
      border: "#e4e2e2",
      title: "#e683d9",
      text: "#75eeb2",
      icon: "#0480ef",
      accent: "#e683d9",
      stroke: "#e4e2e2",
      muted: "#75eeb2",
    },
  },
  cobalt2: {
    name: "cobalt2",
    label: "Cobalt2",
    mode: "dark",
    core: {
      background: "#15232d",
      border: "#e4e2e2",
      title: "#ffc600",
      text: "#0088ff",
      icon: "#ff5cc4",
      accent: "#ffc600",
      stroke: "#e4e2e2",
      muted: "#0088ff",
    },
  },
  synthwave: {
    name: "synthwave",
    label: "Synthwave",
    mode: "dark",
    core: {
      background: "#2b213a",
      border: "#e4e2e2",
      title: "#e2e9ec",
      text: "#e5289e",
      icon: "#ef8539",
      accent: "#e2e9ec",
      stroke: "#e4e2e2",
      muted: "#e5289e",
    },
  },
  dracula: {
    name: "dracula",
    label: "Dracula",
    mode: "dark",
    core: {
      background: "#282a36",
      border: "#e4e2e2",
      title: "#ff6e96",
      text: "#f8f8f2",
      icon: "#79dafa",
      accent: "#ff6e96",
      stroke: "#e4e2e2",
      muted: "#f8f8f2",
    },
  },
  nord: {
    name: "nord",
    label: "Nord",
    mode: "dark",
    core: {
      background: "#2e3440",
      border: "#e4e2e2",
      title: "#81a1c1",
      text: "#d8dee9",
      icon: "#88c0d0",
      accent: "#81a1c1",
      stroke: "#e4e2e2",
      muted: "#d8dee9",
    },
  },
  monokai: {
    name: "monokai",
    label: "Monokai",
    mode: "dark",
    core: {
      background: "#272822",
      border: "#e4e2e2",
      title: "#a6e22e",
      text: "#66d9ef",
      icon: "#f92672",
      accent: "#a6e22e",
      stroke: "#e4e2e2",
      muted: "#66d9ef",
    },
  },
  "solarized-dark": {
    name: "solarized-dark",
    label: "Solarized Dark",
    mode: "dark",
    core: {
      background: "#002b36",
      border: "#e4e2e2",
      title: "#268bd2",
      text: "#93a1a1",
      icon: "#2aa198",
      accent: "#268bd2",
      stroke: "#e4e2e2",
      muted: "#93a1a1",
    },
  },
  "solarized-light": {
    name: "solarized-light",
    label: "Solarized Light",
    mode: "light",
    core: {
      background: "#fdf6e3",
      border: "#93a1a1",
      title: "#268bd2",
      text: "#657b83",
      icon: "#2aa198",
      accent: "#268bd2",
      stroke: "#93a1a1",
      muted: "#657b83",
    },
  },
  "catppuccin-latte": {
    name: "catppuccin-latte",
    label: "Catppuccin Latte",
    mode: "light",
    core: {
      background: "#eff1f5",
      border: "#ccd0da",
      title: "#1e66f5",
      text: "#4c4f69",
      icon: "#8839ef",
      accent: "#1e66f5",
      stroke: "#ccd0da",
      muted: "#6c6f85",
    },
  },
  "catppuccin-frappe": {
    name: "catppuccin-frappe",
    label: "Catppuccin Frappé",
    mode: "dark",
    core: {
      background: "#303446",
      border: "#414559",
      title: "#8caaee",
      text: "#c6d0f5",
      icon: "#ca9ee6",
      accent: "#8caaee",
      stroke: "#414559",
      muted: "#a5adce",
    },
  },
  "catppuccin-macchiato": {
    name: "catppuccin-macchiato",
    label: "Catppuccin Macchiato",
    mode: "dark",
    core: {
      background: "#24273a",
      border: "#363a4f",
      title: "#8aadf4",
      text: "#cad3f5",
      icon: "#c6a0f6",
      accent: "#8aadf4",
      stroke: "#363a4f",
      muted: "#a5adcb",
    },
  },
  "catppuccin-mocha": {
    name: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    mode: "dark",
    core: {
      background: "#1e1e2e",
      border: "#313244",
      title: "#89b4fa",
      text: "#cdd6f4",
      icon: "#cba6f7",
      accent: "#89b4fa",
      stroke: "#313244",
      muted: "#a6adc8",
    },
  },
  "github-light": {
    name: "github-light",
    label: "GitHub Light",
    mode: "light",
    core: {
      background: "#ffffff",
      border: "#d0d7de",
      title: "#0969da",
      text: "#1f2328",
      icon: "#57606a",
      accent: "#0969da",
      stroke: "#d0d7de",
      muted: "#57606a",
    },
  },
  "github-dark": {
    name: "github-dark",
    label: "GitHub Dark",
    mode: "dark",
    core: {
      background: "#0d1117",
      border: "#30363d",
      title: "#58a6ff",
      text: "#c9d1d9",
      icon: "#8b949e",
      accent: "#58a6ff",
      stroke: "#30363d",
      muted: "#8b949e",
    },
  },
  "github-dark-dimmed": {
    name: "github-dark-dimmed",
    label: "GitHub Dark Dimmed",
    mode: "dark",
    core: {
      background: "#22272e",
      border: "#444c56",
      title: "#539bf5",
      text: "#adbac7",
      icon: "#768390",
      accent: "#539bf5",
      stroke: "#444c56",
      muted: "#768390",
    },
  },
  vue: {
    name: "vue",
    label: "Vue",
    mode: "light",
    core: {
      background: "#ffffff",
      border: "#41b883",
      title: "#41b883",
      text: "#273849",
      icon: "#35495e",
      accent: "#41b883",
      stroke: "#41b883",
      muted: "#273849",
    },
  },
  "vue-dark": {
    name: "vue-dark",
    label: "Vue Dark",
    mode: "dark",
    core: {
      background: "#273849",
      border: "#41b883",
      title: "#41b883",
      text: "#ffffff",
      icon: "#35495e",
      accent: "#41b883",
      stroke: "#41b883",
      muted: "#ffffff",
    },
  },
  "shades-of-purple": {
    name: "shades-of-purple",
    label: "Shades of Purple",
    mode: "dark",
    core: {
      background: "#2d2b55",
      border: "#e4e2e2",
      title: "#fad000",
      text: "#a599e9",
      icon: "#9efeff",
      accent: "#fad000",
      stroke: "#e4e2e2",
      muted: "#a599e9",
    },
  },
  nightowl: {
    name: "nightowl",
    label: "Night Owl",
    mode: "dark",
    core: {
      background: "#011627",
      border: "#e4e2e2",
      title: "#c792ea",
      text: "#7fdbca",
      icon: "#addb67",
      accent: "#c792ea",
      stroke: "#e4e2e2",
      muted: "#7fdbca",
    },
  },
  gotham: {
    name: "gotham",
    label: "Gotham",
    mode: "dark",
    core: {
      background: "#0c1014",
      border: "#e4e2e2",
      title: "#2aa889",
      text: "#99d1ce",
      icon: "#2a9292",
      accent: "#2aa889",
      stroke: "#e4e2e2",
      muted: "#99d1ce",
    },
  },
  "material-palenight": {
    name: "material-palenight",
    label: "Material Palenight",
    mode: "dark",
    core: {
      background: "#292d3e",
      border: "#e4e2e2",
      title: "#c792ea",
      text: "#a6accd",
      icon: "#89ddff",
      accent: "#c792ea",
      stroke: "#e4e2e2",
      muted: "#a6accd",
    },
  },
  "ayu-mirage": {
    name: "ayu-mirage",
    label: "Ayu Mirage",
    mode: "dark",
    core: {
      background: "#1f2430",
      border: "#e4e2e2",
      title: "#ffd580",
      text: "#cbccc6",
      icon: "#73d0ff",
      accent: "#ffd580",
      stroke: "#e4e2e2",
      muted: "#cbccc6",
    },
  },
  "midnight-purple": {
    name: "midnight-purple",
    label: "Midnight Purple",
    mode: "dark",
    core: {
      background: "#000000",
      border: "#e4e2e2",
      title: "#8000ff",
      text: "#ffffff",
      icon: "#df7ce6",
      accent: "#8000ff",
      stroke: "#e4e2e2",
      muted: "#ffffff",
    },
  },
  calm: {
    name: "calm",
    label: "Calm",
    mode: "dark",
    core: {
      background: "#151527",
      border: "#e4e2e2",
      title: "#e07a5f",
      text: "#e5c5c5",
      icon: "#81b29a",
      accent: "#e07a5f",
      stroke: "#e4e2e2",
      muted: "#e5c5c5",
    },
  },
  react: {
    name: "react",
    label: "React",
    mode: "dark",
    core: {
      background: "#20232a",
      border: "#e4e2e2",
      title: "#61dafb",
      text: "#a2f3ff",
      icon: "#61dafb",
      accent: "#61dafb",
      stroke: "#e4e2e2",
      muted: "#a2f3ff",
    },
  },
  blueberry: {
    name: "blueberry",
    label: "Blueberry",
    mode: "light",
    core: {
      background: "#f8f9fe",
      border: "#a1a3ff",
      title: "#4d5eff",
      text: "#575e6c",
      icon: "#88a4ff",
      accent: "#4d5eff",
      stroke: "#a1a3ff",
      muted: "#575e6c",
    },
  },
  "dark-aura": {
    name: "dark-aura",
    label: "Dark Aura",
    mode: "dark",
    core: {
      background: "#040f0f",
      border: "#e4e2e2",
      title: "#ffabee",
      text: "#8f9494",
      icon: "#f78166",
      accent: "#ffabee",
      stroke: "#e4e2e2",
      muted: "#8f9494",
    },
  },
  panda: {
    name: "panda",
    label: "Panda",
    mode: "dark",
    core: {
      background: "#1c1f24",
      border: "#e4e2e2",
      title: "#19f9d8",
      text: "#ff9ac1",
      icon: "#ffb86c",
      accent: "#19f9d8",
      stroke: "#e4e2e2",
      muted: "#ff9ac1",
    },
  },
  "rose-pine": {
    name: "rose-pine",
    label: "Rosé Pine",
    mode: "dark",
    core: {
      background: "#191724",
      border: "#e4e2e2",
      title: "#ebbcba",
      text: "#e0def4",
      icon: "#9ccfd8",
      accent: "#ebbcba",
      stroke: "#e4e2e2",
      muted: "#908caa",
    },
  },
  algolia: {
    name: "algolia",
    label: "Algolia",
    mode: "dark",
    core: {
      background: "#050f2c",
      border: "#e4e2e2",
      title: "#00aeff",
      text: "#ffffff",
      icon: "#e2e2e3",
      accent: "#00aeff",
      stroke: "#e4e2e2",
      muted: "#ffffff",
    },
  },
  swift: {
    name: "swift",
    label: "Swift",
    mode: "light",
    core: {
      background: "#fffbf7",
      border: "#ff8c00",
      title: "#f05138",
      text: "#333333",
      icon: "#ff8c00",
      accent: "#f05138",
      stroke: "#ff8c00",
      muted: "#333333",
    },
  },
};

export const DEFAULT_THEME_NAME = "default";

export function getTheme(name: string | undefined | null): ThemeDefinition {
  if (!name) return THEMES[DEFAULT_THEME_NAME];
  return THEMES[name] ?? THEMES[DEFAULT_THEME_NAME];
}

export function listThemes(): ThemeDefinition[] {
  return Object.values(THEMES);
}
